### ISSUE TITLE
A question and some hashes

### ISSUE THREAD

**Issue by ate47** [shiversoftdev/t8-src#3]
Hello, great job with this repo

I was wondering if the hashmap you're using is public or not? Like the [GreyhoundPackageIndex](https://github.com/Scobalula/GreyhoundPackageIndex), but for the strings/scripts.

Also this week I found some hashes and other sub directories using the GreyhoundPackageIndex, COD API results and a lot of guess, if you want to add them to this repository:

- `scripts/weapons`
- `scripts/weapons/mp`
- `scripts/killstreaks`
- `scripts/killstreaks/mp`
- `scripts/abilities`
- `scripts/abilities/gadgets`
- `scripts/wz`
- `scripts/zm_common/talisman`
- `scripts/zm/weapons`
- ...

[the hashes](https://github.com/ate47/t8-src/blob/main/find.txt)

**Comment by shiversoftdev** [comment]
Hello, thanks for your contribution!

The hash database I have is not public and basically just an aggregate of all the variable names we have from all the scripts we have from old games, etc. 

I will get these additional hashes added when I have a chance

**Comment by ate47** [comment]
Ok, I will try to build something similar with these information, thanks!

**Comment by xCortlandx** [comment]
....
